### ISSUE TITLE
does not support nested jobs (jobs in folders)

### ISSUE THREAD

**Issue by mrdfuse** [jbossorg/jira-jenkins-gadget#11]
When you have a Jenkins job in a folder (using the free Cloudbees folder plugin), the plugin doesn't seem to work as the url structure for nested jobs is different:
Regular job: jenkinsurl/job/jobname
Nested job: jenkinsurl/job/parentfolder/job/childjobname

As a workaround I tried specifying 'parentfolder/job/childjobname' as job name, which should work when I look at the source code, the json api url from Jenkins is the same as for a normal job, just append 'api/json' to the whole url.
But somehow the slashes in the jobname get escaped twice resulting in "parentfolder%252Fjob%252Fchildjobname" when I think it should be "parentfolder%2Fjob%2Fchildjobname".
 
I only see one encoding step: return surl + "job/" + encodeURIComponent(prefs.getString("jenkins_job_name"));
and spaces are only encoded once so I'm not sure where the double encoding comes from, I'm not familiar with Jira gadgets.

**Comment by qnxer** [comment]
Does this gadget store its data in a file that can be edited by a programmer?  Where?

The ability for nested branch job URLs is also required for  the build-all-branches plugin.

**Comment by velias** [comment]
Hi, probably best solution will be not to encode slash in the entered job name. I'll try to find some time to implement this. Do you know some public jenkins instance nested job where I can test this?

**Comment by qnxer** [comment]
Hi-

I do not know of such a public Jenkins web server; I might be able to look.

To test, perhaps you can append slash and dot to the Jenkins job name in your widget, which the Jenkins server might shrink and ignore as an unnecessary path segment:

e.g.   http://my-server-name:8080/job/my-job-name/./api/json

It is kind of you to consider a change, thank you.

**Comment by velias** [comment]
Implemented in plugin version 1.9 which has been just pushed into marketplace
