### ISSUE TITLE
We are trying to update the Jira DC to 9.4LTS from 8.20.11

### ISSUE THREAD

**Issue by SrinivasKanagala11** [jbossorg/jira-jenkins-gadget#14]
Hi

We are trying to update the Jira DC to 9.4LTS from 8.20.11. after checking this add-on compatibility in Jira, it says it is incompatible.

https://marketplace.atlassian.com/apps/1211102/jenkins-hudson-build-status-gadget?hosting=server&tab=overviewthis add-on in marketplace, it says it support till for Jira Server 4.0 - 9.3.1 [and more](https://marketplace.atlassian.com/apps/1211102/jenkins-hudson-build-status-gadget/version-history)

Regards,
Srinivas

**Comment by velias** [comment]
Hi. 
I'm updating jira compatibility of this add-on occasionally, typically on request from the Marketplace which sends me email. Currently it is on 9.6 I think.
But I'm not able to provide DC support unfortunately, as this is free plugin but DC compatibility used to have lots of requirements.
Thanks for understanding.
